/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef AUTOUPDATE-IPTV_PRIVATE_H
#define AUTOUPDATE-IPTV_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.1.2"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	2
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.1.2"
#define FILE_DESCRIPTION	"Auto Update for IPTV M3U"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.1.2"

#endif /*AUTOUPDATE-IPTV_PRIVATE_H*/
